[package]
name = "cartesian_merkle_tree"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.12.0"

[dev-dependencies]
snforge_std = "0.48.1"
assert_macros = "2.12.0"

[lib]

# [[target.starknet-contract]]

[tool.snforge]
# This should suppress the external contracts warning for components
exit_first = true

[script]
test = "snforge test"
