[package]
name = "cartesian_merkle_tree"
version = "0.1.0"
edition = "2024_07"
authors = ["Alex Metelli <alex-metelli@gmx.com>"]
description = "Cairo implementation of Cartesian Merkle Trees - efficient cryptographic data structure combining BST, heap, and Merkle tree properties"
documentation = "https://github.com/ametel01/cartesian-merkle-tree"
readme = "README.md"
homepage = "https://github.com/ametel01/cartesian-merkle-tree"
repository = "https://github.com/ametel01/cartesian-merkle-tree"
license = "MIT"
keywords = [
    "merkle-tree",
    "cryptography",
    "cairo",
    "starknet",
    "data-structures",
]

[package.urls]
"Research Paper" = "https://arxiv.org/abs/2504.10944"
"Bug Reports" = "https://github.com/ametel01/cartesian-merkle-tree/issues"

[dependencies]
starknet = "2.12.0"

[dev-dependencies]
snforge_std = "0.48.1"
assert_macros = "2.12.0"

[lib]

[tool.snforge]
# This should suppress the external contracts warning for components
exit_first = true
