name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.2.0)'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  # First run CI checks
  ci-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Scarb
      uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: 2.12.0
    
    - name: Setup Starknet Foundry
      uses: foundry-rs/setup-snfoundry@v3
      with:
        starknet-foundry-version: 0.48.1
    
    - name: Build
      run: scarb build
    
    - name: Format check
      run: scarb fmt --check
    
    - name: Run tests
      run: snforge test
    
    - name: Lint
      run: scarb lint
      continue-on-error: true

  publish:
    runs-on: ubuntu-latest
    needs: ci-check
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Scarb
      uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: 2.12.0
    
    - name: Verify version
      run: |
        TOML_VERSION=$(grep "^version" Scarb.toml | cut -d'"' -f2)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          if [ "$TOML_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch: Scarb.toml has $TOML_VERSION but tag is $TAG_VERSION"
            exit 1
          fi
        fi
        echo "Version: $TOML_VERSION"
        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
    
    - name: Build package
      run: scarb build
    
    # Tests already ran in ci-check job
    
    - name: Package for publication
      run: scarb package
    
    - name: Publish to registry
      env:
        SCARB_REGISTRY_AUTH_TOKEN: ${{ secrets.SCARB_REGISTRY_AUTH_TOKEN }}
      run: |
        if [ -n "$SCARB_REGISTRY_AUTH_TOKEN" ]; then
          scarb publish
          echo "✅ Package published successfully"
        else
          echo "⚠️ No auth token found, skipping publication"
          echo "To enable automatic publishing, add SCARB_REGISTRY_AUTH_TOKEN to repository secrets"
        fi
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/package/*.tar.zst
        generate_release_notes: true
        body: |
          ## Installation
          
          Add to your `Scarb.toml`:
          ```toml
          [dependencies]
          cartesian_merkle_tree = "${{ env.TAG_VERSION }}"
          ```
          
          ## Documentation
          
          📚 [View documentation](https://ametel01.github.io/cartesian-merkle-tree/)
          
          ## What's Changed
          
          See the full changelog below.